// Generated by https://quicktype.io

import { CustomReaction, ReactionUsage } from '../structures/Reaction';
import { Team } from '../structures/Team';
import { User } from '../structures/User';

export interface Me {
    updateMessage: null;
    user: User;
    teams: Team[];
    customReactions: CustomReaction[];
    reactionUsages: ReactionUsage[];
    landingUrl: boolean;
}
