import { APIGroup } from './Group';
import { APIMeasurements } from './Measurements';
import { APIMember } from './Member';
import { APITeamRole } from './Role';
import { APIWebhook } from './Webhook';

export interface APITeam {
    additionalGameInfo: unknown;
    additionalInfo: {
        platform: string;
    };
    alphaInfo: unknown;
    alwaysShowTeamHome: boolean;
    autoSyncDiscordRoles: boolean;
    bannerImages: unknown;
    baseGroup: APIGroup;
    bio: string | null;
    bots: any[];
    canInviteMembers?: boolean;
    canManageTournaments?: boolean;
    canUpdateTeam?: boolean;
    characteristics: string | null;
    createdAt: string;
    customizationInfo: unknown;
    deafenedMembers?: any[];
    description: string;
    discordGuildId: string | null;
    discordServerName: string | null;
    flair: any[];
    followerCount: number;
    followingGroups: string[] | null;
    games: any[];
    homeBannerImageLg: string | null;
    homeBannerImageMd: string | null;
    homeBannerImageSm: string | null;
    id: string;
    insightsInfo: unknown;
    isAdmin?: boolean;
    isFavorite?: boolean;
    isPro: boolean;
    isPublic: boolean;
    isRecruiting: boolean;
    isUserApplicant: boolean;
    isUserBannedFromTeam: boolean;
    isUserInvited: boolean;
    isVerified: boolean;
    lfmStatusByGameId: unknown;
    measurements: APIMeasurements;
    members: APIMember[];
    mutedMembers: any[];
    memberCount?: string;
    membershipRole: string;
    name: string;
    notificationPreference: string | null;
    ownerId: string;
    profilePicture: string;
    rankNames: string | null;
    roleIds?: number[] | null;
    rolesById: {
        [key: string]: APITeamRole;
    };
    rolesVersion: number;
    socialInfo: unknown;
    status: string | null;
    subdomain: string;
    subscriptionInfo: string | null;
    teamDashImage: string | null;
    teamPreferences: string | null;
    timezone: string | null;
    type: string | null;
    upsell: null;
    userFollowsTeam: boolean;
    webhooks: APIWebhook[];
}

export interface APIPartialTeam {
    id: string;
    name: string;
    subdomain: string;
    activity: any[];
    games: string[] | null[];
    profilePicture: string;
    teamDashImage: string;
    homeBannerImageSm: string;
    homeBannerImageMd: string;
    homeBannerImageLg: string;
    gameIds: string[] | null;
    bannerImages: string[] | null[];
    memberCount: number;
}
